[tool.black]
line-length = 88
target-version = ['py36', 'py37', 'py38']
include = '\.pyi?$'
exclude = '''
/(
    /data
  | .git
)/
'''

[tool.flake8]
max-line-length = 88
extend-ignore = E203

[tool.isort]
profile = "black"
line_length = 88

[tool.isort]
profile = "black"
line_length = 88

[tool.pre_commit]
exclude = "^$"
require_serial = true
hooks = [
    "flake8",
    "isort",
    "mypy",
]
